# Generated by Django 5.2.14 on 2026-05-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='title',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer_email',
            field=models.EmailField(default='test@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(default='TKT-000', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
